FROM node:22-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm install

COPY . .


RUN npm run build

COPY ./portfolio.json ./dist/portfolio.json

EXPOSE 8000


CMD ["npm", "run", "start"]